// Mock data for Agency Admin dashboard
export const AGENCY = {
  id: "ag_sunrise",
  name: "Sunrise Home Health",
  tagline: "Care in every zip code · Austin & Round Rock",
  logo: "SH",
  plan: "Growth",
  seatsUsed: 12,
  seatsTotal: 20,
  monthlyCost: 780,
  billingCycle: "monthly",
  hipaaScore: 98,
  admin: {
    name: "Priya Nair",
    title: "Agency Director",
    email: "priya@sunrisehh.demo",
    avatar:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
  },
};

export const NURSES_SEED = [
  {
    id: "n_amara",
    name: "Amara Okafor, RN",
    email: "amara@sunrisehh.demo",
    zone: "Zone 3 · Austin Metro",
    status: "active",
    onboarded: "2025-11-04",
    lastActive: "2m ago",
    visitsToday: 6,
    weeklySaved: 214,
    role: "Registered Nurse",
    avatar:
      "https://images.unsplash.com/photo-1594824476967-48c8b964273f?crop=entropy&cs=srgb&fm=jpg&w=200&q=80",
    currentStop: "Eleanor M. · in visit",
    complianceOk: true,
  },
  {
    id: "n_marcus",
    name: "Marcus Bell, LPN",
    email: "marcus@sunrisehh.demo",
    zone: "Zone 1 · North Austin",
    status: "active",
    onboarded: "2025-09-18",
    lastActive: "8m ago",
    visitsToday: 4,
    weeklySaved: 168,
    role: "Licensed Practical Nurse",
    avatar: null,
    currentStop: "Driving to stop 3",
    complianceOk: true,
  },
  {
    id: "n_devi",
    name: "Devi Rao, RN",
    email: "devi@sunrisehh.demo",
    zone: "Zone 5 · South Austin",
    status: "active",
    onboarded: "2025-10-22",
    lastActive: "14m ago",
    visitsToday: 5,
    weeklySaved: 195,
    role: "Registered Nurse",
    avatar: null,
    currentStop: "En route · Cedar Park",
    complianceOk: true,
  },
  {
    id: "n_jonah",
    name: "Jonah Reyes, RN",
    email: "jonah@sunrisehh.demo",
    zone: "Zone 4 · Round Rock",
    status: "pending",
    onboarded: null,
    lastActive: "—",
    visitsToday: 0,
    weeklySaved: 0,
    role: "Registered Nurse",
    avatar: null,
    currentStop: null,
    complianceOk: false,
  },
  {
    id: "n_priya",
    name: "Priya Suresh, LPN",
    email: "priyas@sunrisehh.demo",
    zone: "Zone 2 · Pflugerville",
    status: "active",
    onboarded: "2025-08-11",
    lastActive: "1h ago",
    visitsToday: 3,
    weeklySaved: 132,
    role: "Licensed Practical Nurse",
    avatar: null,
    currentStop: "On break",
    complianceOk: true,
  },
  {
    id: "n_derek",
    name: "Derek Vance, RN",
    email: "derek@sunrisehh.demo",
    zone: "Zone 6 · Georgetown",
    status: "inactive",
    onboarded: "2025-06-30",
    lastActive: "3d ago",
    visitsToday: 0,
    weeklySaved: 0,
    role: "Registered Nurse",
    avatar: null,
    currentStop: null,
    complianceOk: true,
  },
];

export const LIVE_ACTIVITY_SEED = [
  { t: "09:52", nurseId: "n_amara", label: "Completed visit — Eleanor M.", type: "done" },
  { t: "09:48", nurseId: "n_devi", label: "Voice note transcribed — Mary L.", type: "note" },
  { t: "09:41", nurseId: "n_marcus", label: "Started visit — Thomas R.", type: "start" },
  { t: "09:33", nurseId: "n_amara", label: "Route re-optimized · saved 12 min", type: "route" },
  { t: "09:22", nurseId: "n_priya", label: "Break started · 12 min", type: "break" },
  { t: "09:15", nurseId: "n_devi", label: "PHI accessed — Alma H.", type: "phi" },
  { t: "09:04", nurseId: "n_marcus", label: "Signed in", type: "auth" },
];

export const AGENCY_CLIENTS = [
  { id: "ac1", name: "Eleanor M.", nurseId: "n_amara", city: "Austin, TX", condition: "Post-op knee", visitsWeek: 3, phone: "+1 (512) 555-0142", address: "3421 Elm St, Austin, TX 78701", dob: "Mar 14, 1945", window: "9:00–11:00 AM", lastVisit: "Yesterday", priority: "high", caregiverName: "James M. (son)", caregiverPhone: "+1 (512) 555-0198", flags: ["Fall risk", "Hearing aid"] },
  { id: "ac2", name: "Rafael T.", nurseId: "n_amara", city: "Round Rock, TX", condition: "Wound care", visitsWeek: 2, phone: "+1 (512) 555-0187", address: "1875 Lake Creek Dr, Round Rock, TX 78664", dob: "Aug 22, 1952", window: "10:00 AM–12:00 PM", lastVisit: "2 days ago", priority: "high", caregiverName: "Linda T. (wife)", caregiverPhone: "+1 (512) 555-0191", flags: ["Diabetes", "Antibiotic protocol"] },
  { id: "ac3", name: "Margaret K.", nurseId: "n_amara", city: "Pflugerville, TX", condition: "COPD monitoring", visitsWeek: 3, phone: "+1 (512) 555-0163", address: "890 Pecan St, Pflugerville, TX 78660", dob: "Nov 3, 1938", window: "1:00–3:00 PM", lastVisit: "Yesterday", priority: "medium", caregiverName: null, caregiverPhone: null, flags: ["Oxygen dependent", "Limited mobility"] },
  { id: "ac4", name: "Thomas R.", nurseId: "n_marcus", city: "Austin, TX", condition: "Cardiac follow-up", visitsWeek: 2, phone: "+1 (512) 555-0110", address: "5601 Manor Rd, Austin, TX 78723", dob: "Jun 17, 1949", window: "8:00–10:00 AM", lastVisit: "3 days ago", priority: "high", caregiverName: "Patricia R. (daughter)", caregiverPhone: "+1 (512) 555-0147", flags: ["Pacemaker", "Low sodium diet"] },
  { id: "ac5", name: "Sara P.", nurseId: "n_marcus", city: "Cedar Park, TX", condition: "Diabetes management", visitsWeek: 4, phone: "+1 (512) 555-0201", address: "2412 Brushy Creek Rd, Cedar Park, TX 78613", dob: "Feb 28, 1957", window: "9:30–11:30 AM", lastVisit: "Yesterday", priority: "medium", caregiverName: "David P. (husband)", caregiverPhone: "+1 (512) 555-0202", flags: ["Insulin dependent", "Dietary plan"] },
  { id: "ac6", name: "Alma H.", nurseId: "n_devi", city: "Austin, TX", condition: "Palliative care", visitsWeek: 5, phone: "+1 (512) 555-0174", address: "1200 Barton Springs Rd, Austin, TX 78704", dob: "Apr 9, 1935", window: "10:00 AM–12:00 PM", lastVisit: "Today", priority: "high", caregiverName: "Rosa H. (granddaughter)", caregiverPhone: "+1 (512) 555-0178", flags: ["Hospice", "Pain management", "Family alert"] },
  { id: "ac7", name: "Mary L.", nurseId: "n_devi", city: "Buda, TX", condition: "Post-stroke rehab", visitsWeek: 3, phone: "+1 (512) 555-0135", address: "450 Main St, Buda, TX 78610", dob: "Sep 8, 1942", window: "1:00–3:00 PM", lastVisit: "2 days ago", priority: "high", caregiverName: "Carl L. (son)", caregiverPhone: "+1 (512) 555-0136", flags: ["Speech therapy", "Mobility aid"] },
  { id: "ac8", name: "Frank D.", nurseId: "n_priya", city: "Pflugerville, TX", condition: "Vitals monitoring", visitsWeek: 2, phone: "+1 (512) 555-0123", address: "780 Heather Ln, Pflugerville, TX 78660", dob: "Dec 19, 1950", window: "8:00–9:30 AM", lastVisit: "5 days ago", priority: "low", caregiverName: null, caregiverPhone: null, flags: [] },
  { id: "ac9", name: "Yolanda G.", nurseId: "n_priya", city: "Austin, TX", condition: "Chemo aftercare", visitsWeek: 3, phone: "+1 (512) 555-0159", address: "300 E Riverside Dr, Austin, TX 78704", dob: "Jul 5, 1960", window: "11:00 AM–1:00 PM", lastVisit: "Yesterday", priority: "high", caregiverName: "Michael G. (brother)", caregiverPhone: "+1 (512) 555-0160", flags: ["Immunocompromised", "Nausea protocol"] },
];

export const COMPLIANCE_LOG_SEED = [
  { t: "09:52", nurseId: "n_amara", event: "PHI read — Eleanor M.", severity: "info" },
  { t: "09:48", nurseId: "n_devi", event: "Voice note stored (AES-256)", severity: "info" },
  { t: "09:33", nurseId: "n_amara", event: "Route re-optimized", severity: "info" },
  { t: "09:15", nurseId: "n_devi", event: "PHI read — Alma H.", severity: "info" },
  { t: "08:41", nurseId: "n_marcus", event: "Login from new device", severity: "warn" },
  { t: "08:04", nurseId: "n_amara", event: "MFA challenge passed", severity: "info" },
  { t: "07:58", nurseId: "n_priya", event: "PHI export attempted · blocked", severity: "warn" },
];
