// Mock clients & schedule for RouteMe prototype
export const NURSE = {
  name: "Amara Okafor, RN",
  title: "Registered Nurse · Home Health",
  license: "RN #2418906",
  region: "Austin Metro · Zone 3",
  avatar:
    "https://images.unsplash.com/photo-1594824476967-48c8b964273f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwyfHxudXJzZSUyMHBvcnRyYWl0JTIwc21pbGluZ3xlbnwwfHx8fDE3ODQyMzM0OTl8MA&ixlib=rb-4.1.0&q=85",
  weeklySavedMinutes: 214,
  weeklySavedMiles: 38.4,
};

export const CLIENTS_SEED = [
  {
    id: "c1",
    initials: "E.M.",
    fullName: "Eleanor M.",
    dob: "1942-04-11",
    phone: "(512) 555-0142",
    address: "1204 Pecan Grove Ln, Austin, TX",
    window: "08:00 – 09:30",
    duration: 45,
    priority: "high",
    flags: ["Fall risk", "Gate code #4821", "Small dog"],
    condition: "Post-op knee replacement",
    lastVisit: "Yesterday · 08:20",
    photo:
      "https://images.unsplash.com/photo-1668622168008-90faecb4d3cd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MTJ8MHwxfHNlYXJjaHw0fHxzZW5pb3IlMjBwYXRpZW50JTIwcG9ydHJhaXR8ZW58MHx8fHwxNzg0MjMzNDk5fDA&ixlib=rb-4.1.0&q=85",
  },
  {
    id: "c2",
    initials: "R.T.",
    fullName: "Rafael T.",
    dob: "1955-11-02",
    phone: "(512) 555-0187",
    address: "88 Cypress Bend, Round Rock, TX",
    window: "10:00 – 11:00",
    duration: 30,
    priority: "medium",
    flags: ["Diabetic", "Insulin fridge"],
    condition: "Type II Diabetes · Wound care",
    lastVisit: "3 days ago",
    photo: null,
  },
  {
    id: "c3",
    initials: "M.K.",
    fullName: "Margaret K.",
    dob: "1938-07-19",
    phone: "(512) 555-0230",
    address: "56 Willow Creek, Pflugerville, TX",
    window: "11:45 – 12:45",
    duration: 50,
    priority: "high",
    flags: ["Oxygen", "Hearing aid", "Cat"],
    condition: "COPD monitoring",
    lastVisit: "Yesterday",
    photo: null,
  },
  {
    id: "c4",
    initials: "J.O.",
    fullName: "Jerome O.",
    dob: "1961-02-24",
    phone: "(512) 555-0311",
    address: "742 Live Oak Rd, Austin, TX",
    window: "13:30 – 14:15",
    duration: 25,
    priority: "low",
    flags: ["Stairs · 2nd floor"],
    condition: "Cardiac follow-up",
    lastVisit: "1 week ago",
    photo: null,
  },
  {
    id: "c5",
    initials: "L.V.",
    fullName: "Lucía V.",
    dob: "1949-09-08",
    phone: "(512) 555-0398",
    address: "310 Bluebonnet Trail, Cedar Park, TX",
    window: "15:00 – 15:45",
    duration: 40,
    priority: "medium",
    flags: ["Spanish preferred", "Family present"],
    condition: "Chemo aftercare",
    lastVisit: "4 days ago",
    photo: null,
  },
  {
    id: "c6",
    initials: "H.B.",
    fullName: "Harold B.",
    dob: "1944-12-30",
    phone: "(512) 555-0421",
    address: "22 Sagebrush Way, Georgetown, TX",
    window: "16:15 – 17:00",
    duration: 30,
    priority: "medium",
    flags: ["Dementia care", "Ring loud"],
    condition: "Memory care · vitals",
    lastVisit: "Yesterday",
    photo: null,
  },
];

// Positions on the 1000x600 stylized map viewbox
export const MAP_STOPS = [
  { id: "c1", x: 180, y: 430, label: "1" },
  { id: "c2", x: 320, y: 260, label: "2" },
  { id: "c3", x: 490, y: 170, label: "3" },
  { id: "c4", x: 620, y: 320, label: "4" },
  { id: "c5", x: 760, y: 240, label: "5" },
  { id: "c6", x: 870, y: 420, label: "6" },
];

export const AUDIT_LOG = [
  { t: "08:14", label: "PHI access — Eleanor M.", type: "read" },
  { t: "08:41", label: "Voice note transcribed", type: "note" },
  { t: "09:02", label: "Route re-optimized", type: "route" },
  { t: "09:37", label: "Vitals uploaded — Rafael T.", type: "write" },
  { t: "10:16", label: "PHI access — Margaret K.", type: "read" },
];

export const MOCK_TRANSCRIPT = [
  "Patient reports mild swelling at incision site,",
  " no signs of infection.",
  " Vitals within normal range — BP 128 over 78,",
  " pulse 72, temp 98.4.",
  " Reinforced fall precautions and reviewed medication schedule.",
  " Next visit tomorrow at 08:15.",
];
