// SOAP note export utilities — print & PDF via standalone HTML

export function openPrintWindow(note, client) {
  const win = window.open("", "_blank");
  if (!win) {
    // Popup blocked — fall back to window.print()
    window.print();
    return;
  }

  const signedBlock = note.signed
    ? `<p style="margin-top:1rem;font-size:0.85rem;color:#166534;border-top:2px solid #166534;padding-top:0.75rem;">
        <strong>Signed &amp; locked</strong> — ${note.author} · ${new Date(note.signedAt).toLocaleString()}
       </p>`
    : `<p style="margin-top:1rem;font-size:0.85rem;color:#92400e;border-top:1px dashed #d97706;padding-top:0.75rem;">
        <strong>Draft</strong> — not yet signed
       </p>`;

  const addendums = note.addendums?.length
    ? `<div style="margin-top:1.5rem;border-top:2px solid #e7e5e4;padding-top:1rem;">
         <h3 style="font-size:0.75rem;text-transform:uppercase;letter-spacing:0.15em;color:#a8a29e;margin-bottom:0.5rem;">
           Addendum thread · immutable
         </h3>
         ${note.addendums.map(a => `
           <div style="border-left:3px solid #d95d39;padding-left:0.75rem;margin-bottom:0.75rem;">
             <p style="font-size:0.7rem;color:#a8a29e;text-transform:uppercase;letter-spacing:0.1em;">
               ${a.reason} · ${new Date(a.addedAt).toLocaleString()} · ${a.author}
             </p>
             <p style="margin:0.25rem 0 0;font-size:0.85rem;">${a.text}</p>
           </div>
         `).join("")}
       </div>`
    : "";

  const icdBlock = note.icd10Codes?.length
    ? `<div style="margin-top:0.75rem;">
         ${note.icd10Codes.map(c => `<code style="background:#f5f5f4;padding:0.15rem 0.4rem;border-radius:4px;font-size:0.75rem;margin-right:0.35rem;color:#d95d39;font-weight:600;">${c.code}</code>`).join("")}
         <span style="font-size:0.7rem;color:#78716c;margin-left:0.25rem;">${note.icd10Codes.map(c => c.label).join(", ")}</span>
       </div>`
    : "";

  const lateBadge = note.lateEntry
    ? `<span style="display:inline-block;font-size:0.65rem;text-transform:uppercase;letter-spacing:0.1em;background:#fef2f2;color:#991b1b;border:1px solid #fecaca;border-radius:999px;padding:0.1rem 0.5rem;margin-left:0.5rem;">Late entry</span>`
    : "";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SOAP Note — ${client?.fullName || "Unknown"}</title>
  <style>
    @page { margin: 0.75in; }
    body { font-family: Georgia, "Times New Roman", serif; font-size: 12pt; line-height: 1.6; color: #1c1917; background: white; max-width: 7in; margin: 0 auto; padding: 1in 0; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
    .meta { font-size: 0.8rem; color: #78716c; margin-bottom: 1.5rem; }
    .meta span { margin-right: 1rem; }
    .section { margin-bottom: 1.25rem; }
    .section h3 { font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.1em; color: #d95d39; margin-bottom: 0.25rem; }
    .section p { margin: 0; white-space: pre-line; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e7e5e4; font-size: 0.75rem; color: #a8a29e; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:0.5rem;">
    <h1>SOAP Note</h1>
    ${lateBadge}
  </div>
  <div class="meta">
    <span>Patient: <strong>${client?.fullName || "Unknown"}</strong></span>
    <span>DOB: ${client?.dob || "—"}</span>
    <span>Date: ${new Date(note.serviceAt).toLocaleDateString()}</span>
    <span>Template: ${note.templateLabel || "General"}</span>
  </div>
  <div class="meta">
    <span>Author: ${note.author}</span>
    <span>Entered: ${new Date(note.entryAt).toLocaleString()}</span>
    ${note.signed ? `<span>Signed: ${new Date(note.signedAt).toLocaleString()}</span>` : ""}
  </div>

  <div class="section">
    <h3>S — Subjective</h3>
    <p>${note.subjective || "<em>Not documented</em>"}</p>
  </div>
  <div class="section">
    <h3>O — Objective</h3>
    <p>${note.objective || "<em>Not documented</em>"}</p>
  </div>
  <div class="section">
    <h3>A — Assessment</h3>
    <p>${note.assessment || "<em>Not documented</em>"}</p>
    ${icdBlock}
  </div>
  <div class="section">
    <h3>P — Plan</h3>
    <p>${note.plan || "<em>Not documented</em>"}</p>
  </div>

  ${signedBlock}
  ${addendums}

  <div class="footer">
    Generated by RouteMe · ${new Date().toLocaleString()}
    ${note.lateEntry ? "· Late entry (flagged)" : ""}
  </div>
  <script>
    window.onload = function() { window.print(); };
  <\\/script>
</body>
</html>`;

  win.document.write(html);
  win.document.close();
}