// Mock data for RouteMe Super Admin (Platform) console
// Multi-agency, independent nurses, full-PHI clients, platform audit log, security events, billing.

export const PLATFORM = {
  name: "RouteMe Platform",
  env: "production",
  version: "v1.4.2",
  region: "us-central-1",
  build: "6f2a91c",
};

export const SUPER_ADMIN_ME = {
  id: "sa_root",
  name: "Dr. Isla Fernández",
  title: "Platform Owner",
  email: "root@routeme.platform",
  role: "Owner",
  avatar: null,
  initials: "IF",
  mfaEnabled: true,
};

export const AGENCIES_SEED = [
  {
    id: "ag_sunrise",
    name: "Sunrise Home Health",
    logo: "SH",
    city: "Austin, TX",
    plan: "Growth",
    seatsUsed: 12,
    seatsTotal: 20,
    mrr: 780,
    hipaaScore: 98,
    status: "active",
    director: { name: "Priya Nair", email: "priya@sunrisehh.demo" },
    nurses: 12,
    clients: 47,
    createdAt: "2025-05-14",
  },
  {
    id: "ag_bayside",
    name: "Bayside Nursing Group",
    logo: "BN",
    city: "San Diego, CA",
    plan: "Scale",
    seatsUsed: 34,
    seatsTotal: 50,
    mrr: 2350,
    hipaaScore: 94,
    status: "active",
    director: { name: "Marcus Yeoh", email: "marcus@bayside.demo" },
    nurses: 34,
    clients: 128,
    createdAt: "2024-11-02",
  },
  {
    id: "ag_northstar",
    name: "Northstar Care Collective",
    logo: "NC",
    city: "Minneapolis, MN",
    plan: "Growth",
    seatsUsed: 18,
    seatsTotal: 25,
    mrr: 980,
    hipaaScore: 91,
    status: "active",
    director: { name: "Lena Kowalski", email: "lena@northstar.demo" },
    nurses: 18,
    clients: 64,
    createdAt: "2025-02-19",
  },
  {
    id: "ag_evergreen",
    name: "Evergreen Home Nurses",
    logo: "EG",
    city: "Portland, OR",
    plan: "Starter",
    seatsUsed: 6,
    seatsTotal: 10,
    mrr: 320,
    hipaaScore: 88,
    status: "trial",
    director: { name: "Jonah Reyes", email: "jonah@evergreen.demo" },
    nurses: 6,
    clients: 22,
    createdAt: "2026-01-08",
  },
  {
    id: "ag_atlas",
    name: "Atlas Mobile Health",
    logo: "AT",
    city: "Miami, FL",
    plan: "Scale",
    seatsUsed: 41,
    seatsTotal: 60,
    mrr: 2890,
    hipaaScore: 82,
    status: "attention",
    director: { name: "Camila Reyes", email: "camila@atlas.demo" },
    nurses: 41,
    clients: 156,
    createdAt: "2024-08-30",
  },
  {
    id: "ag_pinewood",
    name: "Pinewood Hospice & Home",
    logo: "PW",
    city: "Denver, CO",
    plan: "Growth",
    seatsUsed: 14,
    seatsTotal: 20,
    mrr: 780,
    hipaaScore: 96,
    status: "active",
    director: { name: "Dr. Aaron Vale", email: "aaron@pinewood.demo" },
    nurses: 14,
    clients: 58,
    createdAt: "2025-06-22",
  },
];

// Global nurses — some attached to agencies (agencyId), some independent (agencyId=null)
export const GLOBAL_NURSES_SEED = [
  { id: "gn_amara", name: "Amara Okafor, RN", email: "amara@sunrisehh.demo", role: "Registered Nurse", agencyId: "ag_sunrise", zone: "Zone 3 · Austin", status: "active", visitsToday: 6, lastActive: "2m ago", license: "RN #2418906", licenseState: "TX", licenseExpires: "2027-04-11", complianceOk: true, mfaEnabled: true },
  { id: "gn_marcus", name: "Marcus Bell, LPN", email: "marcus@sunrisehh.demo", role: "LPN", agencyId: "ag_sunrise", zone: "Zone 1 · Austin", status: "active", visitsToday: 4, lastActive: "8m ago", license: "LPN #55129", licenseState: "TX", licenseExpires: "2026-08-01", complianceOk: true, mfaEnabled: true },
  { id: "gn_devi", name: "Devi Rao, RN", email: "devi@sunrisehh.demo", role: "Registered Nurse", agencyId: "ag_sunrise", zone: "Zone 5 · Austin", status: "active", visitsToday: 5, lastActive: "14m ago", license: "RN #2712004", licenseState: "TX", licenseExpires: "2027-01-30", complianceOk: true, mfaEnabled: true },
  { id: "gn_theo", name: "Theo Kim, NP", email: "theo@bayside.demo", role: "Nurse Practitioner", agencyId: "ag_bayside", zone: "SD North County", status: "active", visitsToday: 3, lastActive: "1m ago", license: "NP #83201", licenseState: "CA", licenseExpires: "2027-11-11", complianceOk: true, mfaEnabled: true },
  { id: "gn_bri", name: "Brianna Ortiz, RN", email: "bri@bayside.demo", role: "Registered Nurse", agencyId: "ag_bayside", zone: "SD Downtown", status: "active", visitsToday: 7, lastActive: "just now", license: "RN #99172", licenseState: "CA", licenseExpires: "2028-02-14", complianceOk: true, mfaEnabled: false },
  { id: "gn_hank", name: "Hank Ellis, RN", email: "hank@atlas.demo", role: "Registered Nurse", agencyId: "ag_atlas", zone: "Miami Beach", status: "suspended", visitsToday: 0, lastActive: "3d ago", license: "RN #77102", licenseState: "FL", licenseExpires: "2026-03-04", complianceOk: false, mfaEnabled: false },
  { id: "gn_yui", name: "Yui Tanaka, RN", email: "yui@northstar.demo", role: "Registered Nurse", agencyId: "ag_northstar", zone: "Minneapolis W", status: "active", visitsToday: 5, lastActive: "20m ago", license: "RN #33218", licenseState: "MN", licenseExpires: "2027-07-19", complianceOk: true, mfaEnabled: true },
  { id: "gn_ren", name: "Ren Alvarez, LPN", email: "ren@pinewood.demo", role: "LPN", agencyId: "ag_pinewood", zone: "Denver S", status: "active", visitsToday: 4, lastActive: "3m ago", license: "LPN #12009", licenseState: "CO", licenseExpires: "2026-12-01", complianceOk: true, mfaEnabled: true },
  { id: "gn_mira", name: "Mira Ashton, RN", email: "mira@evergreen.demo", role: "Registered Nurse", agencyId: "ag_evergreen", zone: "Portland E", status: "pending", visitsToday: 0, lastActive: "—", license: "RN #40015", licenseState: "OR", licenseExpires: "2027-09-22", complianceOk: false, mfaEnabled: false },
  // Independent nurses — no agency
  { id: "gn_indira", name: "Indira Bhatt, RN", email: "indira.bhatt@routeme.io", role: "Independent RN", agencyId: null, zone: "Chicago", status: "active", visitsToday: 3, lastActive: "5m ago", license: "RN #61120", licenseState: "IL", licenseExpires: "2027-03-08", complianceOk: true, mfaEnabled: true },
  { id: "gn_sol", name: "Sol Ramirez, LPN", email: "sol.r@routeme.io", role: "Independent LPN", agencyId: null, zone: "Phoenix", status: "active", visitsToday: 2, lastActive: "22m ago", license: "LPN #48771", licenseState: "AZ", licenseExpires: "2026-10-15", complianceOk: true, mfaEnabled: true },
  { id: "gn_wren", name: "Wren Delacroix, RN", email: "wren@routeme.io", role: "Independent RN", agencyId: null, zone: "New Orleans", status: "active", visitsToday: 4, lastActive: "1h ago", license: "RN #82214", licenseState: "LA", licenseExpires: "2028-05-30", complianceOk: true, mfaEnabled: true },
  { id: "gn_ori", name: "Ori Lindqvist, NP", email: "ori@routeme.io", role: "Independent NP", agencyId: null, zone: "Seattle", status: "attention", visitsToday: 1, lastActive: "2d ago", license: "NP #29118", licenseState: "WA", licenseExpires: "2026-02-28", complianceOk: false, mfaEnabled: true },
  { id: "gn_lyra", name: "Lyra Voss, RN", email: "lyra@routeme.io", role: "Independent RN", agencyId: null, zone: "Boston", status: "active", visitsToday: 5, lastActive: "12m ago", license: "RN #55019", licenseState: "MA", licenseExpires: "2027-11-04", complianceOk: true, mfaEnabled: true },
  { id: "gn_ash", name: "Ash Delacroix, LPN", email: "ash@routeme.io", role: "Independent LPN", agencyId: null, zone: "Nashville", status: "pending", visitsToday: 0, lastActive: "—", license: "LPN #71209", licenseState: "TN", licenseExpires: "2027-06-19", complianceOk: false, mfaEnabled: false },
];

// Global clients with FULL PHI. Access is HIPAA-audited on reveal.
export const GLOBAL_CLIENTS_SEED = [
  {
    id: "gc_eleanor",
    fullName: "Eleanor Mabry",
    dob: "1942-04-11",
    sex: "F",
    ssnLast4: "4821",
    mrn: "MRN-A0421-EL",
    phone: "(512) 555-0142",
    email: "eleanor.mabry@example.com",
    address: "1204 Pecan Grove Ln, Austin, TX 78745",
    agencyId: "ag_sunrise",
    nurseId: "gn_amara",
    insurance: { provider: "Medicare Part A", policyNo: "1EG4-TE5-MK72", group: "—" },
    emergencyContact: { name: "Rachel Mabry (daughter)", phone: "(512) 555-0197", relation: "Daughter" },
    allergies: ["Penicillin", "Latex"],
    medications: ["Metformin 500mg", "Lisinopril 10mg", "Warfarin 2mg"],
    conditions: ["Post-op knee replacement", "Type II Diabetes", "Hypertension"],
    notes: "Fall risk. Gate code #4821. Small dog on premises.",
    lastVisit: "2026-02-13 08:20",
    createdAt: "2025-11-04",
  },
  {
    id: "gc_rafael",
    fullName: "Rafael Torres",
    dob: "1955-11-02",
    sex: "M",
    ssnLast4: "7712",
    mrn: "MRN-A0511-RT",
    phone: "(512) 555-0187",
    email: "raf.torres@example.com",
    address: "88 Cypress Bend, Round Rock, TX 78665",
    agencyId: "ag_sunrise",
    nurseId: "gn_amara",
    insurance: { provider: "Blue Cross TX", policyNo: "BCTX-2298-11", group: "GRP-441" },
    emergencyContact: { name: "Maria Torres (wife)", phone: "(512) 555-0188", relation: "Spouse" },
    allergies: ["Sulfa drugs"],
    medications: ["Insulin glargine", "Atorvastatin 20mg"],
    conditions: ["Type II Diabetes", "Chronic wound care"],
    notes: "Insulin stored in fridge. Wife assists.",
    lastVisit: "2026-02-11 10:15",
    createdAt: "2025-09-18",
  },
  {
    id: "gc_alma",
    fullName: "Alma Herrera",
    dob: "1938-06-04",
    sex: "F",
    ssnLast4: "2201",
    mrn: "MRN-A0611-AH",
    phone: "(512) 555-0413",
    email: null,
    address: "224 Palm Ave, Austin, TX 78703",
    agencyId: "ag_sunrise",
    nurseId: "gn_devi",
    insurance: { provider: "Medicare + Medicaid", policyNo: "1FT2-90X-2201", group: "—" },
    emergencyContact: { name: "Luis Herrera (son)", phone: "(512) 555-0414", relation: "Son" },
    allergies: ["None reported"],
    medications: ["Morphine 5mg PRN", "Ondansetron 4mg"],
    conditions: ["Stage IV pancreatic cancer", "Palliative"],
    notes: "Palliative care · DNR on file. Family present.",
    lastVisit: "2026-02-14 09:15",
    createdAt: "2025-08-11",
  },
  {
    id: "gc_thomas",
    fullName: "Thomas Reyes",
    dob: "1949-01-22",
    sex: "M",
    ssnLast4: "9040",
    mrn: "MRN-B1201-TR",
    phone: "(619) 555-0233",
    email: "treyes@example.com",
    address: "3110 Ocean Ct, San Diego, CA 92109",
    agencyId: "ag_bayside",
    nurseId: "gn_bri",
    insurance: { provider: "Kaiser Permanente", policyNo: "KP-8871-CA", group: "GRP-CA-88" },
    emergencyContact: { name: "Rita Reyes (wife)", phone: "(619) 555-0234", relation: "Spouse" },
    allergies: ["Iodine"],
    medications: ["Metoprolol 50mg", "Aspirin 81mg"],
    conditions: ["Post-MI cardiac follow-up"],
    notes: "Weekly EKG. Beach house — parking on street.",
    lastVisit: "2026-02-13 11:00",
    createdAt: "2025-04-02",
  },
  {
    id: "gc_yolanda",
    fullName: "Yolanda García",
    dob: "1951-09-30",
    sex: "F",
    ssnLast4: "3319",
    mrn: "MRN-B1305-YG",
    phone: "(619) 555-0499",
    email: null,
    address: "1150 Sunset Cliffs Blvd, San Diego, CA 92107",
    agencyId: "ag_bayside",
    nurseId: "gn_theo",
    insurance: { provider: "Medicare Advantage · Humana", policyNo: "HUM-3319-88", group: "GRP-HM-19" },
    emergencyContact: { name: "Elena García (daughter)", phone: "(619) 555-0501", relation: "Daughter" },
    allergies: ["Codeine"],
    medications: ["Levothyroxine 75mcg", "Tamoxifen 20mg"],
    conditions: ["Breast cancer aftercare", "Hypothyroid"],
    notes: "Spanish preferred. Daughter usually present.",
    lastVisit: "2026-02-12 14:30",
    createdAt: "2025-06-28",
  },
  {
    id: "gc_horace",
    fullName: "Horace Whitman",
    dob: "1940-03-17",
    sex: "M",
    ssnLast4: "1188",
    mrn: "MRN-C2011-HW",
    phone: "(303) 555-0322",
    email: null,
    address: "77 Silverwood Ln, Denver, CO 80202",
    agencyId: "ag_pinewood",
    nurseId: "gn_ren",
    insurance: { provider: "Medicare Part A", policyNo: "1ME-1188-CO", group: "—" },
    emergencyContact: { name: "Ada Whitman (spouse)", phone: "(303) 555-0323", relation: "Spouse" },
    allergies: ["None"],
    medications: ["Donepezil 10mg", "Sertraline 50mg"],
    conditions: ["Late-stage Alzheimer's", "Depression"],
    notes: "Dementia care · ring loud. Caregiver present 24/7.",
    lastVisit: "2026-02-14 16:00",
    createdAt: "2025-07-15",
  },
  {
    id: "gc_bea",
    fullName: "Beatrice Nyström",
    dob: "1946-12-08",
    sex: "F",
    ssnLast4: "5502",
    mrn: "MRN-D3005-BN",
    phone: "(612) 555-0181",
    email: "bea.nystrom@example.com",
    address: "2214 Lake Harriet Pkwy, Minneapolis, MN 55416",
    agencyId: "ag_northstar",
    nurseId: "gn_yui",
    insurance: { provider: "BCBS Minnesota", policyNo: "BCMN-5502-11", group: "GRP-MN-91" },
    emergencyContact: { name: "Erik Nyström (son)", phone: "(612) 555-0182", relation: "Son" },
    allergies: ["Shellfish"],
    medications: ["Rivaroxaban 20mg", "Furosemide 40mg"],
    conditions: ["Atrial fibrillation", "Post-stroke rehab"],
    notes: "Physical therapy 2x/week. Icy driveway in winter.",
    lastVisit: "2026-02-13 09:45",
    createdAt: "2025-10-01",
  },
  {
    id: "gc_frank",
    fullName: "Frank D'Angelo",
    dob: "1959-05-27",
    sex: "M",
    ssnLast4: "6603",
    mrn: "MRN-E4022-FD",
    phone: "(305) 555-0770",
    email: null,
    address: "899 Collins Ave, Miami Beach, FL 33139",
    agencyId: "ag_atlas",
    nurseId: null, // unassigned — attention
    insurance: { provider: "Aetna Medicare", policyNo: "AT-6603-FL", group: "GRP-FL-15" },
    emergencyContact: { name: "Serena D'Angelo (daughter)", phone: "(305) 555-0771", relation: "Daughter" },
    allergies: ["NSAIDs"],
    medications: ["Metoprolol", "Warfarin", "Furosemide"],
    conditions: ["CHF", "Chronic kidney disease stage 3"],
    notes: "Needs reassignment — previous nurse suspended.",
    lastVisit: "2026-02-06 08:30",
    createdAt: "2025-03-11",
  },
  {
    id: "gc_ira",
    fullName: "Ira Nakamura",
    dob: "1968-07-14",
    sex: "M",
    ssnLast4: "8829",
    mrn: "IND-0011-IN",
    phone: "(312) 555-0128",
    email: "ira.n@example.com",
    address: "412 W Chicago Ave, Chicago, IL 60654",
    agencyId: null, // independent client — direct with independent nurse
    nurseId: "gn_indira",
    insurance: { provider: "Self-pay", policyNo: "—", group: "—" },
    emergencyContact: { name: "Kenji Nakamura (brother)", phone: "(312) 555-0129", relation: "Brother" },
    allergies: ["Peanuts"],
    medications: ["Insulin lispro"],
    conditions: ["Type I Diabetes"],
    notes: "Independent client — direct-pay via Indira Bhatt.",
    lastVisit: "2026-02-12 07:00",
    createdAt: "2025-12-01",
  },
  {
    id: "gc_maren",
    fullName: "Maren Vogt",
    dob: "1972-02-19",
    sex: "F",
    ssnLast4: "1049",
    mrn: "IND-0022-MV",
    phone: "(206) 555-0219",
    email: "maren.v@example.com",
    address: "1200 Alaskan Way, Seattle, WA 98101",
    agencyId: null,
    nurseId: "gn_ori",
    insurance: { provider: "Premera Blue Cross", policyNo: "PB-1049-WA", group: "GRP-WA-09" },
    emergencyContact: { name: "Jonas Vogt (husband)", phone: "(206) 555-0220", relation: "Spouse" },
    allergies: ["Bee stings"],
    medications: ["Prednisone 5mg", "Methotrexate 15mg"],
    conditions: ["Rheumatoid arthritis"],
    notes: "Weekly infusion prep. Home has stairs.",
    lastVisit: "2026-02-10 15:30",
    createdAt: "2026-01-15",
  },
];

export const SUPER_ADMINS_SEED = [
  { id: "sa_root", name: "Dr. Isla Fernández", email: "root@routeme.platform", role: "Owner", initials: "IF", lastActive: "just now", mfaEnabled: true, status: "active" },
  { id: "sa_pearl", name: "Pearl Odom", email: "pearl@routeme.platform", role: "Compliance", initials: "PO", lastActive: "18m ago", mfaEnabled: true, status: "active" },
  { id: "sa_dev", name: "Devon Ricci", email: "devon@routeme.platform", role: "Support", initials: "DR", lastActive: "1h ago", mfaEnabled: true, status: "active" },
  { id: "sa_kai", name: "Kai Nishimura", email: "kai@routeme.platform", role: "Read-only", initials: "KN", lastActive: "3d ago", mfaEnabled: false, status: "inactive" },
  { id: "sa_ave", name: "Avery Booker", email: "avery@routeme.platform", role: "Support", initials: "AB", lastActive: "2h ago", mfaEnabled: true, status: "active" },
];

export const GLOBAL_AUDIT_SEED = [
  { t: "10:42", actorId: "sa_root", actorName: "Isla Fernández", actorRole: "Owner", action: "PHI reveal", resource: "Client · Eleanor Mabry", agencyId: "ag_sunrise", severity: "warn", ip: "10.0.14.22" },
  { t: "10:38", actorId: "gn_bri", actorName: "Brianna Ortiz", actorRole: "Nurse", action: "Visit completed", resource: "Client · Thomas Reyes", agencyId: "ag_bayside", severity: "info", ip: "10.2.18.11" },
  { t: "10:31", actorId: "sa_pearl", actorName: "Pearl Odom", actorRole: "Compliance", actorRoleColor: "sage", action: "Audit export (CSV)", resource: "30-day HIPAA report", agencyId: null, severity: "info", ip: "10.0.14.9" },
  { t: "10:22", actorId: "ag_atlas_admin", actorName: "Camila Reyes", actorRole: "Agency Director", action: "Nurse suspended", resource: "Hank Ellis (gn_hank)", agencyId: "ag_atlas", severity: "warn", ip: "10.4.22.55" },
  { t: "10:12", actorId: "gn_amara", actorName: "Amara Okafor", actorRole: "Nurse", action: "Voice note stored (AES-256)", resource: "Client · Eleanor Mabry", agencyId: "ag_sunrise", severity: "info", ip: "10.2.18.4" },
  { t: "09:58", actorId: "sa_root", actorName: "Isla Fernández", actorRole: "Owner", action: "Impersonation started", resource: "Director · Camila Reyes (Atlas)", agencyId: "ag_atlas", severity: "warn", ip: "10.0.14.22" },
  { t: "09:47", actorId: "gn_indira", actorName: "Indira Bhatt", actorRole: "Independent RN", action: "PHI read", resource: "Client · Ira Nakamura", agencyId: null, severity: "info", ip: "10.5.22.101" },
  { t: "09:33", actorId: "system", actorName: "System", actorRole: "Automated", action: "Route optimizer ran", resource: "12 nurses · 6 zones", agencyId: null, severity: "info", ip: "—" },
  { t: "09:21", actorId: "unknown", actorName: "unknown@—", actorRole: "Anonymous", action: "Failed login (5 attempts)", resource: "Bayside director portal", agencyId: "ag_bayside", severity: "critical", ip: "203.0.113.42" },
  { t: "09:14", actorId: "sa_dev", actorName: "Devon Ricci", actorRole: "Support", action: "Feature flag toggled", resource: "voice_notes_beta → ON", agencyId: null, severity: "info", ip: "10.0.14.71" },
  { t: "09:02", actorId: "gn_devi", actorName: "Devi Rao", actorRole: "Nurse", action: "MFA challenge passed", resource: "auth.session", agencyId: "ag_sunrise", severity: "info", ip: "10.2.18.6" },
  { t: "08:44", actorId: "gn_ori", actorName: "Ori Lindqvist", actorRole: "Independent NP", action: "License nearing expiry (12 days)", resource: "NP #29118 · WA", agencyId: null, severity: "warn", ip: "—" },
  { t: "08:31", actorId: "sa_root", actorName: "Isla Fernández", actorRole: "Owner", action: "Agency created", resource: "Atlas Mobile Health", agencyId: "ag_atlas", severity: "info", ip: "10.0.14.22" },
  { t: "08:18", actorId: "system", actorName: "System", actorRole: "Automated", action: "Nightly backup completed", resource: "phi.encrypted · 2.4TB", agencyId: null, severity: "info", ip: "—" },
];

export const ACTIVE_SESSIONS_SEED = [
  { id: "sess_1", userId: "sa_root", name: "Isla Fernández", role: "Owner", device: "MacBook Pro · Chrome 131", ip: "10.0.14.22 · Austin, TX", startedAt: "08:12" },
  { id: "sess_2", userId: "sa_pearl", name: "Pearl Odom", role: "Compliance", device: "Windows · Firefox 128", ip: "10.0.14.9 · Boston, MA", startedAt: "09:41" },
  { id: "sess_3", userId: "sa_dev", name: "Devon Ricci", role: "Support", device: "iPad · Safari", ip: "10.0.14.71 · Remote", startedAt: "10:02" },
  { id: "sess_4", userId: "ag_sunrise_admin", name: "Priya Nair", role: "Agency Director", device: "Mac · Chrome", ip: "72.14.23.19 · Austin, TX", startedAt: "07:58" },
  { id: "sess_5", userId: "gn_bri", name: "Brianna Ortiz", role: "Nurse (Bayside)", device: "iPhone 15 · RouteMe iOS", ip: "10.2.18.11 · San Diego", startedAt: "07:14" },
];

export const SECURITY_EVENTS_SEED = [
  { t: "09:21", type: "brute_force", label: "5 failed logins · Bayside", ip: "203.0.113.42", outcome: "blocked", severity: "critical" },
  { t: "08:44", type: "license_expiry", label: "License expires in 12d · Ori L.", ip: "—", outcome: "notified", severity: "warn" },
  { t: "07:58", type: "new_device", label: "New device sign-in · Priya N.", ip: "72.14.23.19", outcome: "mfa_passed", severity: "info" },
  { t: "07:32", type: "phi_export_blocked", label: "PHI export blocked · Atlas", ip: "10.4.22.55", outcome: "denied", severity: "critical" },
  { t: "06:19", type: "mfa_enrolled", label: "MFA enrolled · Ren A.", ip: "10.3.21.5", outcome: "success", severity: "info" },
];

export const SYSTEM_METRICS = {
  uptime: "99.982%",
  uptime30d: 99.982,
  apiP95Ms: 128,
  apiP99Ms: 342,
  dbStatus: "healthy",
  dbReadIops: 1420,
  dbWriteIops: 380,
  queueDepth: 4,
  workers: 12,
  workersHealthy: 12,
  errorRate24h: 0.02,
  featureFlags: [
    { key: "visit_notes", enabled: true, description: "HIPAA-encrypted visit notes" },
    { key: "multi_stop_optimizer_v2", enabled: true, description: "Traffic-aware route re-optimization" },
    { key: "impersonation", enabled: true, description: "Super admin can view as any director/nurse" },
    { key: "sms_reminders", enabled: false, description: "Twilio SMS for visit reminders" },
    { key: "public_signup", enabled: false, description: "Allow self-serve agency signup" },
    { key: "phi_watermark", enabled: true, description: "Watermark every PHI screen view" },
  ],
};

export const BILLING_LEDGER_SEED = [
  { id: "inv_2601", agencyId: "ag_sunrise", period: "Feb 2026", amount: 780, status: "paid", paidAt: "2026-02-01" },
  { id: "inv_2602", agencyId: "ag_bayside", period: "Feb 2026", amount: 2350, status: "paid", paidAt: "2026-02-01" },
  { id: "inv_2603", agencyId: "ag_northstar", period: "Feb 2026", amount: 980, status: "paid", paidAt: "2026-02-02" },
  { id: "inv_2604", agencyId: "ag_evergreen", period: "Feb 2026", amount: 0, status: "trial", paidAt: null },
  { id: "inv_2605", agencyId: "ag_atlas", period: "Feb 2026", amount: 2890, status: "past_due", paidAt: null },
  { id: "inv_2606", agencyId: "ag_pinewood", period: "Feb 2026", amount: 780, status: "paid", paidAt: "2026-02-03" },
];

export const AGENCY_MAP_PINS = [
  { id: "ag_sunrise", x: 460, y: 420, label: "AUS" },
  { id: "ag_bayside", x: 140, y: 380, label: "SD" },
  { id: "ag_northstar", x: 540, y: 200, label: "MSP" },
  { id: "ag_evergreen", x: 140, y: 180, label: "PDX" },
  { id: "ag_atlas", x: 780, y: 460, label: "MIA" },
  { id: "ag_pinewood", x: 400, y: 280, label: "DEN" },
];
